### ISSUE TITLE
Update repo URL.

### ISSUE THREAD

**Issue by jsi** [enonic/gradle-defaults#8]
After upgrading Artifactory from 5.0.1 to 7.2.3, the real URL to the public repo have changed from:
- https://repo.enonic.com/public
to 
- https://repo.enonic.com/artifactory/public

The old format is supported via redirects, so it will work, but the plugin should be updated to use the new URL.

**Comment by sigdestad** [comment]
Hmm, why do we need to expose a product name in our URL? Seems very strange. Can't we turn this off somehow?

**Comment by sigdestad** [comment]
Don't like this at all..

**Comment by jsi** [comment]
Okay.  We need to find a better solution, so I will close this.
